version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/rustdesk.lpk

update:
  strategy: publish
  version_source:
    type: image
    image: rustdesk

build:
  run_buildscript: false

images:
  - id: rustdesk
    target: service
    service: rustdeskserver
    source: docker.io/czyt/rustdesk-server-s6
    channel: stable
    tag_regex: '^v?\d+\.\d+\.\d+$'
    version_regex: '^v?(?P<version>\d+\.\d+\.\d+)$'
    delivery:
      mode: lazycat

stores:
  official:
    enabled: true
    skip_if_version_exists: true
    create_if_missing: false
    changelog_locales: [zh, en]
  private:
    enabled: true
    skip_if_version_exists: true
    name: RustDesk +
    summary: Published from GitHub Actions
